In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
import pickle
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
## preprcess the data 
## drop irrelevant columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

In [5]:
onehot_encoder_geo = OneHotEncoder()
geography_encoded = onehot_encoder_geo .fit_transform(data[['Geography']])
geography_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
geo_encoded_geo = pd.DataFrame(geography_encoded.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [7]:
## combine the one-hot encoded columns with the original dataframe
data = pd.concat([data.drop(['Geography'], axis=1), geo_encoded_geo], axis=1)

In [8]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [9]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [10]:
## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
## Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
## save the encoders and scaler 
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)
with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

## ANN Implementations

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [15]:
## Build our ANN Model 
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)), ## first HL1 connected to the input layer
        Dense(32, activation='relu'), ## HL2 connected to HL1 or HL2
        Dense(1) ## Output layer connected to HL2
    ]
)

In [16]:
## Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
## Set Up the TensorBoard callback
from  tensorflow.keras.callbacks import TensorBoard, EarlyStopping

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [18]:
## Set up Early Stopping callback
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
## Training the model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=32, callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 7747656192.0000 - mean_absolute_error: 71982.2188 - val_loss: 6707378176.0000 - val_mean_absolute_error: 66939.2344
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6445649408.0000 - mean_absolute_error: 65452.6875 - val_loss: 5433508352.0000 - val_mean_absolute_error: 60599.9258
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4660174848.0000 - mean_absolute_error: 56563.2578 - val_loss: 3782761216.0000 - val_mean_absolute_error: 52270.7695
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3660799232.0000 - mean_absolute_error: 51533.5742 - val_loss: 3526958080.0000 - val_mean_absolute_error: 50732.9219
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3603527936.0000 - mean_absolute_error: 51350.1250 - val_loss: 3472068352.0000 - val_mean_absolute_error: 50417.4531
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3558073600.0000 - mean_absolute_error: 51047.1914 - val_loss: 3458540288.0000 - val_mean_absolute_error: 50323.0391
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3561889280.0000 - mean_absolute_error: 51063.4961 - val_loss: 3459101184.0000 - val_mean_absolute_error: 50362.8672
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3525152000.0000 - mean_absolute_error: 50837.4727 - val_loss: 3470585856.0000 - val_mean_absolute_error: 50443.4766
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3517495552.0000 - mean_absolute_error: 50768.6680 - val_loss: 3670295808.0000 - val_mean_absolute_error: 51424.0000
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3554234880.0000 - mean_absolute_error: 51019.7695 - val_loss: 3487156480.0000 - val_mean_absolute_error: 50544.8750
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3532902656.0000 - mean_absolute_error: 50859.6055 - val_loss: 3446778624.0000 - val_mean_absolute_error: 50308.9453
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3540402432.0000 - mean_absolute_error: 50975.0352 - val_loss: 3495444736.0000 - val_mean_absolute_error: 50497.5312
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3530021120.0000 - mean_absolute_error: 50837.2422 - val_loss: 3597734144.0000 - val_mean_absolute_error: 51085.3320
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3532931840.0000 - mean_absolute_error: 50904.7344 - val_loss: 3492577536.0000 - val_mean_absolute_error: 50433.7031
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3514024192.0000 - mean_absolute_error: 50788.3320 - val_loss: 3473064960.0000 - val_mean_absolute_error: 50484.0469
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3521074944.0000 - mean_absolute_error: 50828.0781 - val_loss: 3457056256.0000 - val_mean_absolute_error: 50402.2344
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3517241344.0000 - mean_absolute_error: 50825.9609 - val_loss: 3467745024.0000 - val_mean_absolute_error: 50446.3281
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3538384896.0000 - mean_absolute_error: 50954.4453 - val_loss: 3475588608.0000 - val_mean_absolute_error: 50406.5078
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3499959552.0000 - mean_absolute_error: 50743.4336 - val_loss: 3568447232.0000 - val_mean_absolute_error: 50975.4844
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3518020352.0000 - mean_absolute_error: 50825.3320 - val_loss: 3678776832.0000 - val_mean_absolute_error: 51290.4648
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3506796032.0000 - mean_absolute_error: 50769.1758 - val_loss: 3474548992.0000 - val_mean_absolute_error: 50516.8125

In [20]:
## Load Tesnorboard Extension
%load_ext tensorboard

In [21]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 24856), started 1:55:56 ago. (Use '!kill 24856' to kill it.)

In [22]:
## Evaluate the model on the test set
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3446778624.0000 - mean_absolute_error: 50308.9453
Test Loss: 3446778624.0, Test MAE: 50308.9453125

In [23]:
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.